const DEFAULT_CAMPAIGNS=[];const EMPTY_RECORDER={active:false,sessionId:null,sessionName:"",startedAt:null,targetUrl:"",eventCount:0};chrome.runtime.onInstalled.addListener(async()=>{const d=await chrome.storage.local.get(["campaigns","xpTotal","activityLog","awards","recorderState","recordedTriggers","journeys","journeyProgress"]),s={};if(!Array.isArray(d.campaigns))s.campaigns=DEFAULT_CAMPAIGNS;if(typeof d.xpTotal!=="number")s.xpTotal=0;if(!Array.isArray(d.activityLog))s.activityLog=[];if(!d.awards||typeof d.awards!=="object")s.awards={};if(!d.recorderState)s.recorderState=EMPTY_RECORDER;if(!Array.isArray(d.recordedTriggers))s.recordedTriggers=[];if(!Array.isArray(d.journeys))s.journeys=[];if(!d.journeyProgress)s.journeyProgress={};if(Object.keys(s).length)await chrome.storage.local.set(s)});function key(c){if(c.frequency==="repeat")return null;if(c.frequency==="daily")return`${c.id}:${new Date().toISOString().slice(0,10)}`;return c.id}async function award(c,url,detail){const d=await chrome.storage.local.get(["xpTotal","activityLog","awards"]),a=d.awards||{},k=key(c);if(k&&a[k])return{ok:true,awarded:false,total:d.xpTotal||0};const xp=Math.max(0,Number(c.xp||0)),total=(d.xpTotal||0)+xp;if(k)a[k]={at:Date.now(),url};const entry={id:crypto.randomUUID(),campaignId:c.id,campaignName:c.name,xp,trigger:c.trigger,url,detail,at:Date.now()},log=[entry,...(d.activityLog||[])].slice(0,100);await chrome.storage.local.set({xpTotal:total,activityLog:log,awards:a});return{ok:true,awarded:true,xp,total,entry}}
function unwrap(u){try{const x=new URL(u);if(/(^|\.)isolation\.zscaler\.com$/i.test(x.hostname)){const raw=x.searchParams.get("original_url");if(raw){try{return decodeURIComponent(raw)}catch{return raw}}}return u}catch{return u||""}}
function norm(u){try{const x=new URL(unwrap(u));return x.origin+x.pathname.replace(/\/$/,"")+x.hash}catch{return String(u||"")}}
function base(u){try{const x=new URL(unwrap(u));return x.origin+x.pathname.replace(/\/$/,"")}catch{return String(u||"")}}
function sameUrl(a,b){a=base(a);b=base(b);return !a||!b||a===b||b.startsWith(a)||a.startsWith(b)}
function label(x){return String(x?.elementText||x?.pageTitle||"").replace(/\s+/g," ").trim().toLowerCase()}
function textSimilar(a,b){a=String(a||"").toLowerCase().trim();b=String(b||"").toLowerCase().trim();return !!a&&!!b&&(a===b||a.includes(b)||b.includes(a))}
function completionMatches(s,e){if(!s||!e||e.action!=="complete")return false;
  // Strongest proof: a success/confirmation message learned at record time must exist again.
  if(s.successText)return textSimilar(s.successText,e.successText);
  // Otherwise allow a distinct completion URL/hash only when it is different from the journey start.
  if(s.distinctUrl)return norm(s.url)===norm(e.url);
  // Otherwise allow a distinct completion heading only when it changed from the starting state.
  if(s.distinctHeading)return textSimilar(s.heading,e.heading);
  // No strong completion evidence was learned. Fail closed rather than award XP early.
  return false;
}
function matches(s,e){if(!s||!e||s.action!==e.action)return false;if(s.action==="complete")return completionMatches(s,e);if(!sameUrl(s.url,e.url))return false;if(s.action==="field")return !s.semanticKey||!e.semanticKey||s.semanticKey===e.semanticKey;if(s.action==="click"||s.action==="submit")return !s.elementText||!e.elementText||textSimilar(s.elementText,e.elementText);return true}
async function showJourneyAward(tab,c,result){if(!result?.awarded||typeof tab!=="number")return;try{await chrome.tabs.sendMessage(tab,{type:"K2_JOURNEY_AWARDED",campaign:c,xp:result.xp,total:result.total})}catch{}}
async function processJourney(e,sender){const d=await chrome.storage.local.get(["campaigns","journeyProgress"]),cs=(d.campaigns||[]).filter(c=>c.enabled&&c.trigger==="journey"&&c.steps?.length),p=d.journeyProgress||{},tab=sender?.tab?.id??e.tabId??"global",done=[];for(const c of cs){const k=`${c.id}:${tab}`;let i=Number(p[k]||0),steps=c.steps;
    // A fresh visit to the recorded starting page begins a fresh attempt. Never carry stale
    // progress (especially a pending completion state) into a new visit.
    if(e.action==="page"&&steps[0]?.action==="page"&&sameUrl(steps[0].url,e.url)){i=1;p[k]=i;continue}
    while(i<steps.length&&steps[i]?.optional)i++;
    if(matches(steps[i],e)){i++;while(i<steps.length&&steps[i]?.optional)i++}
    else if(i===0&&steps[0]?.action==="page"&&steps[1]&&sameUrl(steps[0].url,e.url)&&matches(steps[1],e))i=2;
    else if(matches(steps[0],e))i=1;
    if(i>=steps.length){const result=await award(c,e.url||"",`Completed journey: ${steps.length} semantic step(s)`);done.push({campaign:c,result});await showJourneyAward(typeof tab==="number"?tab:null,c,result);i=0}p[k]=i}await chrome.storage.local.set({journeyProgress:p});return done}
async function record(e,sender){const d=await chrome.storage.local.get(["recorderState","recordedTriggers"]),r=d.recorderState||EMPTY_RECORDER;if(!r.active||!r.sessionId||String(e.url||"").startsWith("chrome-extension://")||e.action==="complete")return{ok:false};const item={id:crypto.randomUUID(),sessionId:r.sessionId,sessionName:r.sessionName||"Recording",at:Date.now(),action:e.action||"unknown",url:unwrap(e.url||sender?.url||""),pageTitle:e.pageTitle||"",selector:e.selector||"",elementText:(e.elementText||"").slice(0,120),destinationUrl:unwrap(e.destinationUrl||""),semanticKey:e.semanticKey||"",fieldType:e.fieldType||"",tabId:sender?.tab?.id??null};const list=[item,...(d.recordedTriggers||[])].slice(0,500),next={...r,eventCount:(r.eventCount||0)+1,lastTabId:item.tabId,lastEventAt:item.at};await chrome.storage.local.set({recordedTriggers:list,recorderState:next});return{ok:true,item}}
function cleanSteps(raw,target,completion){let a=raw.slice().sort((x,y)=>x.at-y.at).map(x=>({...x,url:unwrap(x.url),destinationUrl:unwrap(x.destinationUrl)}));const out=[];for(const x of a){const prev=out[out.length-1];if(x.action==="page"&&prev?.action==="page"&&norm(x.url)===norm(prev.url)){out[out.length-1]=x;continue}if(x.action==="field"&&prev?.action==="field"&&x.semanticKey&&x.semanticKey===prev.semanticKey){out[out.length-1]=x;continue}const dup=prev&&x.action===prev.action&&x.action!=="click"&&x.action!=="submit"&&norm(x.url)===norm(prev.url)&&label(x)===label(prev)&&Math.abs((x.at||0)-(prev.at||0))<250;if(dup)continue;out.push(x)}const mapped=out.map((x,i)=>({id:crypto.randomUUID(),order:i+1,action:x.action,url:norm(x.url),pageTitle:x.pageTitle,selector:x.selector||"",elementText:x.elementText||"",semanticKey:x.semanticKey||"",fieldType:x.fieldType||"",optional:x.action==="field"}));const start=out[0]||{};const completionUrl=norm(completion?.url||out[out.length-1]?.url||target);const startUrl=norm(target||start.url||"");const startHeading=String(start.elementText||start.pageTitle||"").trim();const completionHeading=String(completion?.heading||"").trim();const successText=String(completion?.successText||"").trim();const distinctUrl=!!completionUrl&&!!startUrl&&completionUrl!==startUrl;const distinctHeading=!!completionHeading&&!!startHeading&&!textSimilar(completionHeading,startHeading);mapped.push({id:crypto.randomUUID(),order:mapped.length+1,action:"complete",url:completionUrl,pageTitle:completion?.pageTitle||"",elementText:successText||completionHeading||"Completion state",heading:completionHeading,successText,distinctUrl,distinctHeading,verified:!!(successText||distinctUrl||distinctHeading),completion:true});return mapped}
async function markComplete(){const d=await chrome.storage.local.get(["recorderState","recordedTriggers","journeys"]),r=d.recorderState||EMPTY_RECORDER;if(!r.active||!r.sessionId)return{ok:false,reason:"not-recording"};let completion={action:"complete",url:r.targetUrl||"",elementText:"Completion state",formCount:0};if(Number.isInteger(r.lastTabId))try{completion=await chrome.tabs.sendMessage(r.lastTabId,{type:"K2_CAPTURE_COMPLETION"})||completion}catch{}const raw=(d.recordedTriggers||[]).filter(x=>x.sessionId===r.sessionId),steps=cleanSteps(raw,r.targetUrl,completion);if(steps.length<2)return{ok:false,reason:"no-events"};const journey={id:crypto.randomUUID(),name:r.sessionName||"Recorded K2 journey",createdAt:Date.now(),completedAt:Date.now(),targetUrl:r.targetUrl||"",steps,completionVerified:!!steps.at(-1)?.verified},journeys=[journey,...(d.journeys||[])].slice(0,100),next={...r,active:false,stoppedAt:Date.now(),markedComplete:true,eventCount:steps.length};await chrome.storage.local.set({journeys,recorderState:next});return{ok:true,journey}}
chrome.runtime.onMessage.addListener((m,sender,send)=>{if(m?.type==="K2_AWARD_REQUEST"){award(m.campaign,m.url,m.detail).then(send);return true}if(m?.type==="K2_START_RECORDER"){(async()=>{const r={active:true,sessionId:crypto.randomUUID(),sessionName:(m.sessionName||"K2 activity journey").trim(),targetUrl:(m.targetUrl||"").trim(),startedAt:Date.now(),eventCount:0};await chrome.storage.local.set({recorderState:r});if(r.targetUrl)try{await chrome.tabs.create({url:r.targetUrl})}catch{}send({ok:true,recorderState:r})})();return true}if(m?.type==="K2_STOP_RECORDER"){(async()=>{const d=await chrome.storage.local.get(["recorderState"]),r={...(d.recorderState||EMPTY_RECORDER),active:false,stoppedAt:Date.now()};await chrome.storage.local.set({recorderState:r});send({ok:true})})();return true}if(m?.type==="K2_MARK_COMPLETE"){markComplete().then(send);return true}if(m?.type==="K2_RECORD_EVENT"){record(m.event||{},sender).then(send);return true}if(m?.type==="K2_OBSERVED_EVENT"){processJourney({...m.event,url:unwrap(m.event?.url||"")},sender).then(send);return true}});chrome.tabs.onUpdated.addListener(async(tabId,info,tab)=>{if(info.status!=="complete"||!tab.url||tab.url.startsWith("chrome://")||tab.url.startsWith("chrome-extension://"))return;const e={action:"page",url:unwrap(tab.url),pageTitle:tab.title||"",elementText:tab.title||"",tabId};await processJourney(e,{tab:{id:tabId}});await record(e,{tab:{id:tabId}})});