(()=>{
let recording=false,lastUrl=location.href,stateTimer=null,lastActionKey="",lastActionAt=0,lastFieldAt=0;
const clean=s=>String(s||"").replace(/\s+/g," ").trim();
const looksGenerated=s=>/^[0-9a-f]{8}-[0-9a-f-]{20,}$/i.test(String(s||"").replace(/^#/,""))||/^[0-9a-f]{20,}$/i.test(String(s||"").replace(/^#/,""));
function esc(v){return CSS?.escape?CSS.escape(v):String(v).replace(/([^\w-])/g,"\\$1")}
function visible(el){if(!el||el.nodeType!==1)return false;const r=el.getBoundingClientRect?.();if(!r||r.width<=0||r.height<=0)return false;const cs=getComputedStyle(el);return cs.visibility!=="hidden"&&cs.display!=="none"}
function stableSelector(el){if(!el||el.nodeType!==1)return"";if(el.id&&!looksGenerated(el.id))return`#${esc(el.id)}`;for(const a of["data-testid","data-test","data-qa","name","aria-label"]){const v=el.getAttribute?.(a);if(v&&v.length<80&&!looksGenerated(v)){const s=`${el.tagName.toLowerCase()}[${a}="${String(v).replace(/"/g,'\\"')}"]`;try{if(document.querySelectorAll(s).length===1)return s}catch{}}}return""}
function exactSelector(el){if(!el||el.nodeType!==1)return"";const stable=stableSelector(el);if(stable)return stable;const parts=[];let n=el;for(let depth=0;n&&n.nodeType===1&&depth<8;depth++,n=n.parentElement){const anchor=stableSelector(n);if(anchor){parts.unshift(anchor);break}let p=n.tagName.toLowerCase();const parent=n.parentElement;if(parent){const same=[...parent.children].filter(x=>x.tagName===n.tagName);if(same.length>1)p+=`:nth-of-type(${same.indexOf(n)+1})`}parts.unshift(p);if(n===document.body)break}return parts.join(" > ")}
function shortOwnText(el){if(!el||el.nodeType!==1)return"";const attrs=[el.getAttribute?.("aria-label"),el.getAttribute?.("title"),el.getAttribute?.("value")];for(const v of attrs){const t=clean(v);if(t&&!looksGenerated(t)&&t.length<=100)return t}const direct=[...el.childNodes||[]].filter(n=>n.nodeType===3).map(n=>clean(n.textContent)).filter(Boolean).join(" ");if(direct&&!looksGenerated(direct)&&direct.length<=100)return direct;const all=clean(el.innerText||el.textContent);if(all&&!looksGenerated(all)&&all.length<=100)return all;return""}
function pathElements(e){const p=typeof e.composedPath==="function"?e.composedPath():[];return p.filter(n=>n&&n.nodeType===1)}
function actionElement(e){const path=pathElements(e);for(const n of path){if(n.matches?.("button,a,input[type=button],input[type=submit],[role=button],summary"))return n}for(const n of path.slice(0,10)){let pointer=false;try{pointer=getComputedStyle(n).cursor==="pointer"}catch{}if(n.onclick||n.getAttribute?.("role")==="button"||n.hasAttribute?.("tabindex")||pointer)return n}return e.target?.nodeType===1?e.target:null}
function bestActionLabel(el,e){const candidates=[];for(const n of [el,...pathElements(e).slice(0,10)]){const t=shortOwnText(n);if(t&&t.toLowerCase()!=="div"&&t.toLowerCase()!=="span")candidates.push(t)}if(candidates.length)return candidates.sort((a,b)=>a.length-b.length)[0];const hash=decodeURIComponent(location.hash.replace(/^#/,"")).replace(/[-_]+/g," ").trim();return hash?hash.replace(/\b\w/g,c=>c.toUpperCase()):"Action"}
function contextHeading(el){const root=el?.closest?.("form,section,[role=dialog],[role=region],main,article")||document;for(const h of root.querySelectorAll?.("h1,h2,h3,legend,[role=heading]")||[]){if(visible(h)){const t=clean(h.innerText||h.textContent);if(t&&t.length<=120)return t}}const hash=decodeURIComponent(location.hash.replace(/^#/,"")).replace(/[-_]+/g," ").trim();return hash?hash.replace(/\b\w/g,c=>c.toUpperCase()):"Page"}
function sectionContext(el){const form=el?.closest?.("form");if(form)return`form:${exactSelector(form)||contextHeading(form).toLowerCase()}`;const root=el?.closest?.("section,[role=dialog],[role=region],main,article");return`section:${root?exactSelector(root)||contextHeading(root).toLowerCase():contextHeading(el).toLowerCase()}`}
function controlRole(el){const tag=el?.tagName?.toLowerCase()||"",type=(el?.getAttribute?.("type")||"").toLowerCase();if(tag==="input"&&type==="submit")return"submit-control";if(tag==="button"&&(type==="submit"||el?.closest?.("form")))return"submit-control";if(tag==="a"&&el.href)return"navigation-cta";if(el?.closest?.("form")&&Date.now()-lastFieldAt<30000)return"form-action";return"action-control"}
function fieldLabel(el){if(!el)return"Field";for(const v of [el.getAttribute?.("aria-label"),el.getAttribute?.("placeholder")]){const t=clean(v);if(t&&!looksGenerated(t))return t.slice(0,100)}if(el.id&&!looksGenerated(el.id)){try{const l=document.querySelector(`label[for="${CSS.escape(el.id)}"]`);const t=clean(l?.innerText||l?.textContent);if(t)return t.slice(0,100)}catch{}}const wrap=el.closest?.("label");const wt=clean(wrap?.innerText||wrap?.textContent);if(wt&&!looksGenerated(wt))return wt.slice(0,100);const type=(el.type||el.tagName||"field").toLowerCase();return type==="email"?"Email field":type==="password"?"Password field":type==="tel"?"Phone field":type==="text"?"Text field":"Form field"}
function fieldKey(el){const s=exactSelector(el);if(s)return s;return `${fieldLabel(el).toLowerCase()}|${sectionContext(el)}`}
function successText(){const re=/\b(success|successful|successfully|thank you|thanks|confirmed|confirmation|complete|completed|registered|registration complete|welcome|submitted|received|all set)\b/i;for(const n of [...document.querySelectorAll('[role="alert"],[role="status"],[class*="success"],[id*="success"],[class*="thank"],[id*="thank"],[class*="confirm"],[id*="confirm"],h1,h2,h3')]){if(!visible(n))continue;const t=clean(n.innerText||n.textContent);if(t&&t.length<=220&&re.test(t))return t.slice(0,160)}return""}
function heading(){for(const n of [...document.querySelectorAll("h1,h2,[role=heading]")])if(visible(n)){const t=clean(n.innerText||n.textContent);if(t&&t.length<=160)return t.slice(0,160)}return""}
function snapshot(){return{action:"complete",url:location.href,pageTitle:document.title,heading:heading(),successText:successText(),visibleForms:[...document.querySelectorAll("form")].filter(visible).length,elementText:successText()||heading()||"Completion state"}}
function badge(on){let b=document.getElementById("__k2_recorder_badge");if(!on){b?.remove();return}if(b)return;b=document.createElement("div");b.id="__k2_recorder_badge";b.textContent="● K2 JOURNEY RECORDER";Object.assign(b.style,{position:"fixed",top:"14px",right:"14px",zIndex:"2147483647",padding:"9px 12px",borderRadius:"999px",background:"#061c24",color:"#1de7d8",border:"1px solid rgba(29,231,216,.55)",font:"700 11px system-ui",letterSpacing:".08em",boxShadow:"0 8px 28px rgba(0,0,0,.35)",pointerEvents:"none"});document.documentElement.appendChild(b)}
function toast(c,xp,total){document.getElementById("__k2_xp_toast")?.remove();const b=document.createElement("div");b.id="__k2_xp_toast";b.innerHTML=`<div style="font-size:11px;letter-spacing:.15em;opacity:.75">K2 MISSION COMPLETE</div><div style="font-size:24px;font-weight:900;margin-top:4px">+${xp} XP</div><div style="font-size:13px;margin-top:4px">${c.name}</div><div style="font-size:11px;opacity:.7;margin-top:4px">${total} total XP</div>`;Object.assign(b.style,{position:"fixed",right:"22px",bottom:"22px",zIndex:"2147483647",padding:"16px 18px",minWidth:"220px",borderRadius:"16px",color:"#fff",fontFamily:"system-ui",background:"linear-gradient(145deg,#082832,#07151d)",border:"1px solid rgba(29,231,216,.55)",boxShadow:"0 16px 48px rgba(0,0,0,.42)"});document.documentElement.appendChild(b);setTimeout(()=>b.remove(),5000)}
async function sendObserved(event){try{return await chrome.runtime.sendMessage({type:"K2_OBSERVED_EVENT",event})}catch{}}
async function emit(event){try{await sendObserved(event);if(recording)await chrome.runtime.sendMessage({type:"K2_RECORD_EVENT",event})}catch{}scheduleState()}
function scheduleState(){clearTimeout(stateTimer);stateTimer=setTimeout(()=>sendObserved(snapshot()),700)}
function pageEvent(){if(location.href===lastUrl)return;lastUrl=location.href;emit({action:"page",url:location.href,pageTitle:document.title,elementText:heading()||document.title})}
function captureAction(e){const el=actionElement(e);if(!el||el.closest?.("#__k2_recorder_badge"))return;const before=location.href,label=bestActionLabel(el,e),role=controlRole(el),selector=exactSelector(el),ctx=sectionContext(el),dest=el.closest?.("a")?.href||"";setTimeout(()=>{const after=location.href;let finalLabel=label,finalDest=dest,finalRole=role;if(after!==before&&!finalDest){finalDest=after;if(finalLabel==="Action"){const h=decodeURIComponent(new URL(after).hash.replace(/^#/,"")).replace(/[-_]+/g," ").trim();if(h)finalLabel=`Open ${h.replace(/\b\w/g,c=>c.toUpperCase())}`}finalRole="navigation-cta"}if(finalLabel==="Action"&&Date.now()-lastFieldAt<30000)finalLabel=`Submit ${contextHeading(el)}`;const semanticKey=[finalRole,selector,finalLabel.toLowerCase(),finalDest,ctx].join("|");const now=Date.now();if(semanticKey===lastActionKey&&now-lastActionAt<700)return;lastActionKey=semanticKey;lastActionAt=now;emit({action:"click",url:before,pageTitle:document.title,selector,elementText:finalLabel,destinationUrl:finalDest,semanticKey,controlRole:finalRole,contextKey:ctx})},140)}
document.addEventListener("pointerdown",captureAction,true);
document.addEventListener("submit",e=>{const f=e.target,ctx=sectionContext(f);emit({action:"submit",url:location.href,pageTitle:document.title,selector:exactSelector(f),elementText:`Submit ${contextHeading(f)}`,semanticKey:exactSelector(f)||ctx,contextKey:ctx})},true);
document.addEventListener("change",e=>{const el=e.target;if(!el||!el.matches?.("input,select,textarea")||(el.type||"").toLowerCase()==="hidden")return;lastFieldAt=Date.now();emit({action:"field",url:location.href,pageTitle:document.title,selector:exactSelector(el),elementText:fieldLabel(el),semanticKey:fieldKey(el),fieldType:(el.type||el.tagName||"").toLowerCase(),contextKey:sectionContext(el)})},true);
window.addEventListener("hashchange",()=>setTimeout(pageEvent,0));window.addEventListener("popstate",()=>setTimeout(pageEvent,0));setInterval(pageEvent,600);
try{new MutationObserver(()=>scheduleState()).observe(document.documentElement,{subtree:true,childList:true,attributes:false})}catch{}
chrome.runtime.onMessage.addListener((m,s,send)=>{if(m?.type==="K2_JOURNEY_AWARDED"){toast(m.campaign,m.xp,m.total);return}if(m?.type==="K2_CAPTURE_COMPLETION"){send(snapshot());return true}});
chrome.storage.local.get(["recorderState"]).then(({recorderState:r})=>{recording=!!r?.active;badge(recording);scheduleState()});chrome.storage.onChanged.addListener((c,a)=>{if(a==="local"&&c.recorderState){recording=!!c.recorderState.newValue?.active;badge(recording)}});
})();